---
{{- if eq .Values.stackVersion "1" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: static-cache-init
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
      nodeSelector:
        kubernetes.azure.com/agentpool: linux01
        kubernetes.azure.com/mode: user
        kubernetes.io/os: linux
      containers:
      - name: static-cache-init
        image: {{ include "rendering.image" . }}
        imagePullPolicy: Always
        command:
        - "/bin/sh"
        - "-c"
        - "/app/static-cache.sh"
        volumeMounts:
        - name: rendering-cache
          mountPath: /rendering-cache
          subPath: {{ include "rendering.image_version_tag" . }}
      volumes:
      - name: rendering-cache
        persistentVolumeClaim:
          claimName: rendering-static-cache-{{ .Values.stackVersion }}
      restartPolicy: Never
  backoffLimit: 5
  completions: 1
{{- end }}