---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rendering-static-cache-{{ .Values.stackVersion }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "2"
provisioner: file.csi.azure.com
mountOptions:
  - dir_mode=0777
  - file_mode=0777
parameters:
  skuName: Standard_ZRS
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rendering-static-cache-{{ .Values.stackVersion }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "3"
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  storageClassName: rendering-static-cache-{{ .Values.stackVersion }}
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: rendering-zrs-persistent-volume-{{ .Values.stackVersion }}
    shareName: rendering-static-cache
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rendering-static-cache-{{ .Values.stackVersion }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "4"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rendering-static-cache-{{ .Values.stackVersion }}
  resources:
    requests:
      storage: 10Gi
  volumeName: rendering-static-cache-{{ .Values.stackVersion }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jobreports-rendering-{{ .Values.stackVersion }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "5"
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany 
  storageClassName: rendering-static-cache-{{ .Values.stackVersion }}
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: rendering-zrs-persistent-volume-{{ .Values.stackVersion }}
    shareName: jobreports
    readOnly: false
  mountOptions:
  - dir_mode=0555
  - file_mode=0555
  - uid=1000
  - gid=1000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jobreports-rendering-{{ .Values.stackVersion }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rendering-static-cache-{{ .Values.stackVersion }}
  resources:
    requests:
      storage: 10Gi
  volumeName:  jobreports-rendering-{{ .Values.stackVersion }}