---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rendering.stackName" . }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  sitecore-jss-editing-secret: {{ .Values.secret.sitecore_jss_editing_secret | b64enc  }}
  sitecore-api-key: {{ .Values.secret.sitecore_api_key | b64enc  }}
  akm-am5-charts: {{ .Values.secret.sitecore_akm_am5_charts | b64enc | quote  }}
  akm-am5-maps: {{ .Values.secret.sitecore_akm_am5_maps | b64enc | quote }}
  rendering-apim-singlewebplatform-subscription-key: {{ .Values.secret.rendering_apim_singlewebplatform_subscription_key | b64enc  }}
  google-maps-api-key: {{ .Values.secret.google_maps_api_key | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rendering-zrs-persistent-volume-{{ .Values.stackVersion }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
type: Opaque
data:
  azurestorageaccountkey: {{ .Values.secret.rendering_cache_storage_account_key | b64enc  }}
  azurestorageaccountname: {{ .Values.secret.rendering_cache_storage_account_name | b64enc  }}
{{- if and (eq .Values.stackVersion "1") (eq .Values.location "eur-nl") }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "rendering.cm" . }}
  namespace: {{ .Values.namespace }}
data:
  sitecore-jss-editing-secret: {{ .Values.secret.sitecore_jss_editing_secret | b64enc  }}
  sitecore-api-key: {{ .Values.secret.sitecore_api_key | b64enc  }}
  akm-am5-charts: {{ .Values.secret.sitecore_akm_am5_charts | b64enc | quote }}
  akm-am5-maps: {{ .Values.secret.sitecore_akm_am5_maps | b64enc | quote }}
  rendering-apim-singlewebplatform-subscription-key: {{ .Values.secret.rendering_apim_singlewebplatform_subscription_key | b64enc  }}
  google-maps-api-key: {{ .Values.secret.google_maps_api_key | b64enc | quote }}
{{- end }}
