---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rendering.stackName" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "rendering.stackName" . }}
  ports:
  - protocol: TCP
    port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rendering.stackNameJobsapi" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "rendering.stackNameJobsapi" . }}
  ports:
  - protocol: TCP
    port: 3000

{{- if and (eq .Values.stackVersion "1") (eq .Values.location "eur-nl") }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rendering.cm" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "rendering.cm" . }}
  ports:
  - protocol: TCP
    port: 3000
{{- end }}


